spring:
  application:
    name: personia-hr
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    database: default

personia:
  datasource:
    url: "jdbc:h2:mem:personia"
    username: "sa"

toggles:
  use-persistence: "false"
