spring:
  application:
    name: personia-hr
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    database: default
  datasource:
    url: "jdbc:h2:mem:personia"
    username: "sa"
    password:
    driver-class-name: org.h2.Driver

toggles:
  use-persistence: "true"
